import { storage } from "./storage";
import type { InsertGame } from "@shared/schema";

export async function seedGames() {
  const count = await storage.getGameCount();
  if (count > 0) return;

  const now = new Date();
  const hour = (h: number) => new Date(now.getTime() + h * 3600000);

  const seedData: InsertGame[] = [
    {
      sport: "nfl",
      league: "NFL",
      homeTeam: "Kansas City Chiefs",
      awayTeam: "Buffalo Bills",
      homeScore: 21,
      awayScore: 17,
      status: "live",
      quarter: "Q3",
      timeRemaining: "8:42",
      startTime: hour(-2),
      homeMoneyline: -150,
      awayMoneyline: 130,
      spread: -3.5,
      spreadOdds: -110,
      totalPoints: 49.5,
      overOdds: -110,
      underOdds: -110,
      featured: true,
      homeStats: { passingYards: 245, rushingYards: 98, turnovers: 1, timeOfPossession: "18:32" },
      awayStats: { passingYards: 212, rushingYards: 76, turnovers: 2, timeOfPossession: "14:28" },
    },
    {
      sport: "nfl",
      league: "NFL",
      homeTeam: "San Francisco 49ers",
      awayTeam: "Dallas Cowboys",
      homeScore: 14,
      awayScore: 10,
      status: "live",
      quarter: "Q2",
      timeRemaining: "3:15",
      startTime: hour(-1),
      homeMoneyline: -180,
      awayMoneyline: 155,
      spread: -4.5,
      spreadOdds: -115,
      totalPoints: 45.5,
      overOdds: -105,
      underOdds: -115,
      featured: true,
      homeStats: { passingYards: 156, rushingYards: 67, turnovers: 0, timeOfPossession: "12:45" },
      awayStats: { passingYards: 134, rushingYards: 43, turnovers: 1, timeOfPossession: "10:15" },
    },
    {
      sport: "nba",
      league: "NBA",
      homeTeam: "Boston Celtics",
      awayTeam: "Milwaukee Bucks",
      homeScore: 88,
      awayScore: 82,
      status: "live",
      quarter: "Q4",
      timeRemaining: "5:33",
      startTime: hour(-2),
      homeMoneyline: -220,
      awayMoneyline: 185,
      spread: -6.5,
      spreadOdds: -110,
      totalPoints: 218.5,
      overOdds: -110,
      underOdds: -110,
      featured: true,
      homeStats: { rebounds: 38, assists: 22, steals: 8, blocks: 4, fieldGoalPct: 48.2, threePointPct: 38.5 },
      awayStats: { rebounds: 34, assists: 19, steals: 6, blocks: 3, fieldGoalPct: 44.6, threePointPct: 32.1 },
    },
    {
      sport: "nba",
      league: "NBA",
      homeTeam: "Los Angeles Lakers",
      awayTeam: "Golden State Warriors",
      homeScore: 0,
      awayScore: 0,
      status: "upcoming",
      startTime: hour(3),
      homeMoneyline: 110,
      awayMoneyline: -130,
      spread: 2.5,
      spreadOdds: -110,
      totalPoints: 228.5,
      overOdds: -110,
      underOdds: -110,
      featured: false,
      homeStats: null,
      awayStats: null,
    },
    {
      sport: "nba",
      league: "NBA",
      homeTeam: "Denver Nuggets",
      awayTeam: "Phoenix Suns",
      homeScore: 0,
      awayScore: 0,
      status: "upcoming",
      startTime: hour(5),
      homeMoneyline: -160,
      awayMoneyline: 140,
      spread: -3.5,
      spreadOdds: -110,
      totalPoints: 224.5,
      overOdds: -108,
      underOdds: -112,
      featured: false,
      homeStats: null,
      awayStats: null,
    },
    {
      sport: "soccer",
      league: "Premier League",
      homeTeam: "Arsenal",
      awayTeam: "Manchester City",
      homeScore: 1,
      awayScore: 1,
      status: "live",
      quarter: "2H",
      timeRemaining: "67'",
      startTime: hour(-1),
      homeMoneyline: 145,
      awayMoneyline: 120,
      spread: 0.5,
      spreadOdds: -120,
      totalPoints: 2.5,
      overOdds: 100,
      underOdds: -120,
      featured: true,
      homeStats: { possession: 46, totalShots: 12, shotsOnTarget: 5, fouls: 11, corners: 6, yellowCards: 2, redCards: 0 },
      awayStats: { possession: 54, totalShots: 15, shotsOnTarget: 7, fouls: 9, corners: 8, yellowCards: 1, redCards: 0 },
    },
    {
      sport: "soccer",
      league: "La Liga",
      homeTeam: "Real Madrid",
      awayTeam: "Barcelona",
      homeScore: 0,
      awayScore: 0,
      status: "upcoming",
      startTime: hour(6),
      homeMoneyline: 110,
      awayMoneyline: 105,
      spread: -0.5,
      spreadOdds: -110,
      totalPoints: 2.5,
      overOdds: -105,
      underOdds: -115,
      featured: false,
      homeStats: null,
      awayStats: null,
    },
    {
      sport: "mlb",
      league: "MLB",
      homeTeam: "New York Yankees",
      awayTeam: "Boston Red Sox",
      homeScore: 4,
      awayScore: 3,
      status: "live",
      quarter: "Bot 6th",
      timeRemaining: "",
      startTime: hour(-2),
      homeMoneyline: -145,
      awayMoneyline: 125,
      spread: -1.5,
      spreadOdds: 130,
      totalPoints: 8.5,
      overOdds: -110,
      underOdds: -110,
      featured: false,
      homeStats: { hits: 8, errors: 0, strikeouts: 5, walks: 3 },
      awayStats: { hits: 6, errors: 1, strikeouts: 7, walks: 2 },
    },
    {
      sport: "mlb",
      league: "MLB",
      homeTeam: "Los Angeles Dodgers",
      awayTeam: "San Diego Padres",
      homeScore: 0,
      awayScore: 0,
      status: "upcoming",
      startTime: hour(4),
      homeMoneyline: -165,
      awayMoneyline: 145,
      spread: -1.5,
      spreadOdds: 115,
      totalPoints: 7.5,
      overOdds: -105,
      underOdds: -115,
      featured: false,
      homeStats: null,
      awayStats: null,
    },
    {
      sport: "nfl",
      league: "NFL",
      homeTeam: "Philadelphia Eagles",
      awayTeam: "Miami Dolphins",
      homeScore: 0,
      awayScore: 0,
      status: "upcoming",
      startTime: hour(8),
      homeMoneyline: -135,
      awayMoneyline: 115,
      spread: -2.5,
      spreadOdds: -110,
      totalPoints: 51.5,
      overOdds: -110,
      underOdds: -110,
      featured: false,
      homeStats: null,
      awayStats: null,
    },
  ];

  for (const game of seedData) {
    await storage.createGame(game);
  }

  const demoUser = await storage.getUserByUsername("demo");
  if (!demoUser) {
    await storage.createUser({ username: "demo", password: "demo123" });
  }
}
